[package]
name = "super_rustycom_client"
version = "0.1.0"
authors = ["Santeri Salmijärvi <santeri.salmijarvi@aalto.fi>"]
edition = "2018"

[dependencies]
super-rustycom-core = { path = "../super-rustycom-core" }
clap = "3.2.16"
chrono = "0.4.19"
fern = "0.6.1"
itertools = "0.10.3"
log = "0.4.17"
minifb = "0.23.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
