[package]
name = "super_rustycom_client"
version = "0.1.0"
authors = ["Santeri Salmijärvi <santeri.salmijarvi@aalto.fi>"]
edition = "2018"

[dependencies]
super-rustycom-core = { path = "../super-rustycom-core" }
clap = "2.33.3"
minifb = "0.19.1"
serde = { version = "1.0.117", features = [ "derive" ]}
serde_json = "1.0.59"
